run:
  dir: ./output/run_32k_MSEmonitor

model:
  path: model.keras
  type: TinyTables
  norm_factor: 1.0

output:
  dir: ml_root

samples:
  - name: SingleNeutrino
    input: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/SingleNeutrino_PU200_14_2_X_500k.h5
    output: SingleNeutrino_ml.root
  
  - name: VBF_HToInvisible
    input: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/VBF_HToInvisible_M-125_15_1_X_48k.h5
    output: VBF_HToInvisible_ml.root

  - name: TTbar
    input: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/TT_15_1_X_300k.h5
    output: TTbar_ml.root

  - name: TTToSemileptonic
    input: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/TTToSemileptonic_15_1_X_300k.h5
    output: TTToSemileptonic_ml.root

  - name: TTTo2L2Nu
    input: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/TTTo2L2Nu_15_1_X_500k.h5
    output: TTTo2L2Nu_ml.root

  # - name: VBFHToInvisible
  #   input: ../../dataset/h5_input/140X/VBFHToInvisible_PU200_48k.h5
  #   output: VBFHToInvisible_ml.root

  # - name: QCD
  #   input: ../../dataset/h5_input/140X/QCD_Pt15To3000_PU200_95k.h5
  #   output: QCD_ml.root

  # - name: SingleNeutrino
  #   input: ../../dataset/h5_input/140X/SingleNeutrino_PU200_300k.h5
  #   output: SingleNeutrino_ml.root

  # - name: TTbar_PU200_300k_151X
  #   input: ../../dataset/h5_input/151X/TTbar_PU200_300k_151X.h5
  #   output: TTbar_151X_ml.root

  # - name: TTToSemileptonic_PU200_300k_151X
  #   input: ../../dataset/h5_input/151X/TTToSemileptonic_PU200_300k_151X.h5
  #   output: TTToSemileptonic_151X_ml.root

  # - name: VBF_HToInvisible_PU200_48k_151X
  #   input: ../../dataset/h5_input/151X/VBF_HToInvisible_PU200_48k_151X.h5
  #   output: VBF_HToInv_151X_ml.root
