training:
  input:
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/DYToLL_M50_PTLL200To400_PU200_14_2_X_105k.h5
      max_events: 24000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/DYToLL_M50_PTLL400To600_PU200_14_2_X_104k.h5
      max_events: 24000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/DYToLL_M50_PTLL600ToInf_PU200_14_2_X_93k.h5
      max_events: 24000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/DYToLL_M50_PU200_14_2_X_988k.h5
      max_events: 24000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/GluGluHHTo2B2Tau_PU200_14_2_X_48k.h5
      max_events: 24000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/TT_PU200_14_2_X_299k.h5
      max_events: 48000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/TTTo2L2Nu_PU200_14_2_X_499k.h5
      max_events: 48000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/TTToSemileptonic_PU200_14_2_X_238k.h5
      max_events: 48000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/VBFHToInvisible_PU200_14_2_X_48k.h5
      max_events: 48000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/14_2_X/WJetsToLNu_PU200_14_2_X_32k.h5
      max_events: 24000
  
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/DYto2L-2Jets_MLL-50_PTLL-200to400_2J_15_1_X_105k.h5  
      max_events: 24000
    # - path: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/TTTo2L2Nu_15_1_X_500k.h5
    #   max_events: 24000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/DYto2L-2Jets_MLL-50_PTLL-400to600_2J_15_1_X_100k.h5  
      max_events: 24000
    # - path: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/TTToSemileptonic_15_1_X_300k.h5
    #   max_events: 24000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/DYto2L-2Jets_MLL-50_PTLL-600_2J_15_1_X_97k.h5        
      max_events: 24000
    # - path: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/VBF_HToInvisible_M-125_15_1_X_48k.h5
    #   max_events: 24000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/GluGluToHHTo2B2Tau_node_SM_15_1_X_49k.h5             
      max_events: 24000
    - path: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/WJetsToLNu_15_1_X_34k.h5
      max_events: 24000
    # - path: /home/junwonoh/data/mlmet_dataset/h5_files/15_1_X/TT_15_1_X_300k.h5
    #   max_events: 24000

  output: ./output/run_32k_MSEmonitor
  epochs: 1000
  batch_size: 512
  norm_factor: 1.0
  model: TinyTables

model_cfg:
  NUM_PID: 8
  NUM_ETA: 8
  NUM_PT: 256
  D: 2

quantization:
  enable: true
  gamma:
    total_bits: 9
    integer_bits: 2
  beta:
    total_bits: 9
    integer_bits: 4

gpu:
  use_gpu: false
  gpu_index: 0
  memory_growth: true

callbacks:
  early_stopping_patience: 50
  reduce_lr_patience: 4
  reduce_lr_factor: 0.5
  min_lr: 1.0e-9
  monitor: "val_mean_squared_error"
  # monitor: "val_loss"